#pragma once

#include <vide/concept.hpp>
#include <vide/exception.hpp>
#include <vide/vide.hpp>

#include <cassert>
#include <sstream>


namespace vide {

// =================================================================================================

//! An output archive designed to save data in a compact binary representation
/*! This archive outputs data to a stream in an extremely compact binary
	representation with as little extra metadata as possible.

	This archive does nothing to ensure that the endianness of the saved
	and loaded data is the same.  If you need to have portability over
	architectures with different endianness, use PortableBinaryOutputArchive.

	When using a binary archive and a file stream, you must use the
	std::ios::binary format flag to avoid having your data altered
	inadvertently.

	\ingroup Archives */
class BinaryOutputArchive : public OutputArchive<BinaryOutputArchive, AllowEmptyClassElision | IgnoreNVP | BinaryArchive> {
private:
	std::ostream& itsStream;

public:
	//! Construct, outputting to the provided stream
	/*! @param stream The stream to output to.  Can be a stringstream, a file stream, or
					  even cout! */
	explicit BinaryOutputArchive(std::ostream& stream) :
		itsStream(stream) {
	}

	~BinaryOutputArchive() noexcept = default;

	//! Writes size bytes of data to the output stream
	void saveBinary(const void* data, std::streamsize size) {
		auto const writtenSize = itsStream.rdbuf()->sputn(reinterpret_cast<const char*>(data), size);

		if (writtenSize != size)
			throw Exception("Failed to write " + std::to_string(size) + " bytes to output stream. Wrote " + std::to_string(writtenSize));
	}

	// --- process_as remapping ------------------------------------------------------------------------
public:
	using OutputArchive::process_as;

	template <class As, typename T>
	inline void process_as(As& as, const NameValuePair<T>& t) {
		as(t.value);
	}

	template <class As, typename T>
	inline void process_as(As& as, const SizeTag<T>& t) {
		as(t.size);
	}

	template <class As>
	inline void process_as(As&, const bool t) {
		// This commented code would fix values generated by UB, Not sure if we are interested in this
		// uint8_t value = std::bit_cast<uint8_t>(t);
		// value = value > 0 ? 1 : 0;
		uint8_t value = t;
		assert(value == 0 || value == 1); // If the bool is not 0 or 1 its UB in the caller code
		saveBinary(std::addressof(value), sizeof(value));
	}

	template <class As, binary_serializable_type T>
	inline void process_as(As&, const T& t) {
		saveBinary(std::addressof(t), sizeof(t));
	}

	template <class As, class T>
	inline void process_as(As&, const BinaryData<T>& t) {
		saveBinary(t.data, static_cast<std::streamsize>(t.size));
	}
};

// =================================================================================================

//! An input archive designed to load data saved using BinaryOutputArchive
/*  This archive does nothing to ensure that the endianness of the saved
	and loaded data is the same.  If you need to have portability over
	architectures with different endianness, use PortableBinaryOutputArchive.

	When using a binary archive and a file stream, you must use the
	std::ios::binary format flag to avoid having your data altered
	inadvertently.

	\ingroup Archives */
class BinaryInputArchive : public InputArchive<BinaryInputArchive, AllowEmptyClassElision | IgnoreNVP | BinaryArchive> {
private:
	std::istream::pos_type end;
	std::istream& itsStream;

public:
	//! Construct, loading from the provided stream
	explicit BinaryInputArchive(std::istream& stream) :
		itsStream(stream) {

		const auto begin = itsStream.tellg();
		itsStream.seekg(0, std::ios::end);
		if (itsStream.fail())
			throw Exception("Failed to seek stream to determine binary size.");
		end = itsStream.tellg();
		itsStream.seekg(begin, std::ios::beg);
		if (itsStream.fail())
			throw Exception("Failed to seek stream to determine binary size.");
		reserveMemoryBudget = static_cast<std::size_t>(end - begin) * VIDE_RESERVE_MEMORY_BUDGET_MULTIPLIER;
	}

	~BinaryInputArchive() noexcept = default;

	//! Reads size bytes of data from the input stream
	void loadBinary(void* data, std::streamsize size) {
		const auto readSize = itsStream.rdbuf()->sgetn(reinterpret_cast<char*>(data), size);

		if (readSize != size)
			throw Exception("Failed to read " + std::to_string(size) + " bytes from input stream. Read " + std::to_string(readSize));
	}

	[[nodiscard]] inline std::size_t maximumBinaryReadSize() const {
		const auto pos = itsStream.tellg();
		return end - pos;
	}

	// --- process_as remapping ------------------------------------------------------------------------
public:
	using InputArchive::process_as;

	template <class As, typename T>
	inline void process_as(As& as, NameValuePair<T>& t) {
		as(t.value);
	}

	template <class As, typename T>
	inline void process_as(As& as, SizeTag<T>& t) {
		as(t.size);
	}

	template <class As>
	inline void process_as(As&, bool& t) {
		uint8_t value;
		loadBinary(std::addressof(value), sizeof(value));
		if (value == 0)
			t = false;
		else if (value == 1)
			t = true;
		else
			throw Exception("Invalid bool value \'" + std::to_string(value) + "\' at byte " + std::to_string(static_cast<int64_t>(itsStream.tellg()) - 1));
	}

	template <class As, binary_serializable_type T>
	inline void process_as(As&, T& t) {
		loadBinary(std::addressof(t), sizeof(t));
	}

	template <class As, class T>
	inline void process_as(As&, BinaryData<T>& t) {
		loadBinary(t.data, static_cast<std::streamsize>(t.size));
	}
};

// =================================================================================================

} // namespace vide

// register archives for polymorphic support
VIDE_REGISTER_ARCHIVE(vide::BinaryOutputArchive)
VIDE_REGISTER_ARCHIVE(vide::BinaryInputArchive)
